var express = require("express");
var router = new express.Router();
var deviceModelController = require("../controllers/device_model");
router.get("/", deviceModelController.deviceModelList);
router.get("/make/:id", deviceModelController.deviceMakeModels);
router.get("/:id", deviceModelController.deviceModelDetail);
router.post("/", deviceModelController.deviceModelCreate);
router.delete("/", deviceModelController.deviceModelDelete);
router.put("/", deviceModelController.deviceModelUpdate);
module.exports = router;
